"""
    parameters.jl

The default parameter set the SOCRATES column runs with, as data.
"""

"""
Constants the Atlas LES ran with.

The latent heats were recovered from the Atlas output by requiring
`Q*SED = -(1/ρ) ∂(Q*SDFLX/L)/∂z`, which holds to eight significant figures for the
forward stencil and no other; fusion is derived as their difference, 333600 J/kg.
`density_ice_water` does not reach cloud ice in this stack, so the ice density Atlas
ran M2005 at is set through `cloud_ice_apparent_density`.
"""
const ATLAS_LES_CONSTANTS = (;
    latent_heat_vaporization_at_reference = 2_510_400.0,
    latent_heat_sublimation_at_reference = 2_844_000.0,
    cloud_ice_apparent_density = 500.0,
)

"""
Prognostic EDMFX closure coefficients, 
"""
const EDMFX_CLOSURE_PARAMS = (;
    EDMF_max_surface_area = 0.1,
    EDMF_min_area = 1.0e-5,
    EDMF_max_area = 0.7,
    turb_entr_param_vec = [0.001, 1.0e5],
    entr_inv_tau = 0.0,
    entr_coeff = 0.1,
    min_area_limiter_scale = 0.001,
    min_area_limiter_power = 1.0,
    detr_coeff = 0.0,
    detr_buoy_coeff = 1.0,
    detr_vertdiv_coeff = 0.0,
    detr_massflux_vertdiv_coeff = 0.3,
    max_area_limiter_scale = 0.001,
    max_area_limiter_power = 1.0,
    pressure_normalmode_drag_coeff = 8.0,
)

"""
Non-equilibrium relaxation timescales [s]
"""
const RELAXATION_TIMESCALES = (;
    condensation_evaporation_timescale = 100.0,
    sublimation_deposition_timescale = 10000.0,
)

"""
Sedimentation velocity scaling factors, one per species.

SOCRATES-defined rather than ClimaParams parameters: read back into
[`ScaledTerminalVelocity`](@ref) modes, where 1 reproduces
`ClimaAtmos.DiagnosticTerminalVelocity`.
"""
const TERMINAL_VELOCITY_SCALING_DEFAULTS = (;
    cloud_liquid_terminal_velocity_scaling_factor = 1.0,
    cloud_ice_terminal_velocity_scaling_factor = 1.0,
    rain_terminal_velocity_scaling_factor = 1.0,
    snow_terminal_velocity_scaling_factor = 1.0,
)

"""The whole suite parameter set, layered under the case's own values and any overrides."""
const SOCRATES_PARAMETERS = merge(
    ATLAS_LES_CONSTANTS,
    EDMFX_CLOSURE_PARAMS,
    RELAXATION_TIMESCALES,
    TERMINAL_VELOCITY_SCALING_DEFAULTS,
)

"""
    parameter_overrides(set = SOCRATES_PARAMETERS)

`set` in the `ClimaParams` override form, `name => Dict("value" => …, "type" => …)`.
"""
parameter_overrides(set = SOCRATES_PARAMETERS) = Dict{String, Any}(
    String(name) => Dict{String, Any}("value" => value, "type" => "float") for
    (name, value) in pairs(set)
)

"""
    write_parameter_file(path = config_path(); set = SOCRATES_PARAMETERS)

Write `set` as a `ClimaParams` override TOML, returning `path`. The shipped
`configs/socrates.toml` is this file; nothing reads it to build a run.
"""
function write_parameter_file(
    path::AbstractString = config_path();
    set = SOCRATES_PARAMETERS,
)
    mkpath(dirname(abspath(path)))
    open(path, "w") do io
        println(io, "# Generated by `SOCRATES.write_parameter_file`; edit `src/parameters.jl`.")
        println(io)
        TOML.print(io, parameter_overrides(set))
    end
    return path
end